### ISSUE TITLE
Add number_of_winners as a parameter of create function

### ISSUE THREAD

**Issue by 0x-onigiri** [fukaeridesui/suipstakes#15]
# 概要
- `number_of_winners` を `create` 関数の引数として渡せるようにする
- `number_of_winners` が `min_participants` 以上、 `max_participants` 以下になるように validation を追加する

**Comment by fukaeridesui** [comment]
`number_of_winners`を`u32`へ合わせて変更をする

`min_participants`, `max_participants`は`u32`
`number_of_winners`は`u16`

となっているが、`min_participants`に`u16`で表現できない数値を入力された場合に`number_of_winners`の設定ができなくなるのため
